package com.dpforge.ocubator;

/**
 * Represents a file generated by annotations processor
 */
public class GeneratedFile {

    private final String path;
    private final String content;

    GeneratedFile(final String path, final String content) {
        this.path = path;
        this.content = content;
    }

    /**
     * Path to this file relative to project directory.
     * For example {@code "test/Generated.java"}
     */
    public String getPath() {
        return path;
    }

    /**
     * Get content of this file
     */
    public String getContent() {
        return content;
    }
}
